# Generated by Django 3.2.9 on 2021-12-07 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20211201_1621'),
        ('news', '0002_auto_20211206_1928'),
    ]

    operations = [
    ]
